#!/usr/bin/env bash
# Example ping for ALX 

if [ -z "$1" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

if ! [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
then
	exit 1
fi

ping -c 5 "$1"
