#!/usr/bin/env bash
# configures nginx server to listen on port 80
# rm the previous simbolic linc
rm /etc/nginx/sites-enabled/default
# create a new link to available sites
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
sudo service nginx restart
