#!/usr/bin/env bash
# Configure nginx and stop service frok running
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
