#!/usr/bin/env bash
# script use while and if to print best school
string4="Best School"
n=1
while [ $n -le 10 ]
do
	if [ $n -ne 9 ]
	then
		echo "$string4"
	else
		echo "$string4"
		echo "Hi"
	fi
	(( n++ ))
done
