#!/usr/bin/env bash
# script use while and case to print to screen

n=1

while [ $n -le 20 ]
do
	echo "$n"
	case $n in
		4 )
			echo "bad luck from China" ;;
		9 )
			echo "bad luck from japan" ;;
		17 )
			echo "bad luck from italy" ;;
	esac
	(( n++ ))
done
