#!/usr/bin/env bash
# script use while and case to print to screen
#
# - displays bad luck from china when n equals 4
# - displays bad luck from japan when n equals 9
# - displays bad luck from italy when n equals 17
# ===============================================

n=1

while [ $n -le 20 ]
do
	echo "$n"
	case $n in
		4 )
			echo "bad luck from China"
		;;
		9 )
			echo "bad luck from Japan"
		;;
		17 )
			echo "bad luck from Italy"
		;;
	esac
	(( n++ ))
done
