#!/usr/bin/env bash
# outputs the 12-hour representation of time

hour=0

while (( hour <= 12 ))
do
	echo "Hour: $hour"
	min=1
	while (( min <= 59 ))
	do

		echo "$min"
		(( min++ ))
	done
	(( hour++ ))
done
